### ISSUE TITLE
Error object fields must not be capitalized

### ISSUE THREAD

**Issue by SorJEF** [devicehive/devicehive-.net#6]
Wrong
-----
If a server error occurs, returned JSON object contains capitalized fields. Here is the example:
```js
{  
   "Message":"...",
   "ExceptionMessage":"..." 
}
```

Right
-----
The object fields must not be capitilized to increase consistency through the whole RESTful API.
```js
{  
   "message":"...",
   "exceptionMessage":"..." 
}
```

**Comment by devicehive** [comment]
Fixed this issue by changing 'Message' to 'message' and removing all other properties (message now includes all information about the error).
Note the application has the 'customErrors' setting: when set to 'On', no exception details are disclosed.
