### ISSUE TITLE
Didn't find the /bin/Server/DBMigrator/DeviceHive.DBMigrator.exe file after running the /src/Server/build.cmd 

### ISSUE THREAD

**Issue by thakorjay** [devicehive/devicehive-.net#8]
for deploying the server...i got the above issue...

**Comment by devicehive** [comment]
Could you please provide the build log?

**Comment by thakorjay** [comment]
The peoblem is solved.Because of unreliable connection and authorization
problem of net i didnt get that . Afterwards its solved.
